"""empty message

Revision ID: 146b7b4296cc
Revises: 35800867bcbe
Create Date: 2023-03-15 14:31:47.004530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146b7b4296cc'
down_revision = '35800867bcbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('make', sa.String(length=75), nullable=False),
    sa.Column('model', sa.String(length=75), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('vin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
