"""empty message

Revision ID: 35800867bcbe
Revises: 9a4134cc8b85
Create Date: 2023-03-15 14:23:38.642609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35800867bcbe'
down_revision = '9a4134cc8b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
