"""empty message

Revision ID: 9006b74f0375
Revises: 15e59c812f8b
Create Date: 2023-03-14 14:06:02.803514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9006b74f0375'
down_revision = '15e59c812f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_Token', sa.String(), nullable=False))
        batch_op.drop_constraint('car_user_token_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['car_Token'], ['token'])
        batch_op.drop_column('mileage')
        batch_op.drop_column('price')
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mileage', sa.REAL(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('car_user_token_fkey', 'user', ['user_token'], ['token'])
        batch_op.drop_column('car_Token')

    # ### end Alembic commands ###
